### ISSUE TITLE
是否可以让bot默认监听所有聊天

### ISSUE THREAD

**Issue by artxia** [SharzyL/tg_searcher#1]
先感谢下，这个bot真好用。

说下我的出发点，本意搭建bot是想解决tg的中文搜索问题，当加入很多群组频道以后，全局搜索信息变得非常重要。
所以使用的时候并不想仅仅只搜索某几个频道或群组，如果能提供整体（已加入的群组和频道）搜索，那就可以直接取代tg的搜索框了。。

**Comment by SharzyL** [comment]
目前的架构理论上能够做到。但是有两个问题需要解决：

1. whoosh 目前索引中文的性能不太好，大约一秒索引 100 条左右，如果加入的群组比较多，可能对机器的负担比较重，因此需要进一步调优索引性能。
2. 处理历史消息的策略。有些群可能包含非常多的历史消息，全部索引不现实。

**Comment by artxia** [comment]
> 目前的架构理论上能够做到。但是有两个问题需要解决：
> 
> 1. whoosh 目前索引中文的性能不太好，大约一秒索引 100 条左右，如果加入的群组比较多，可能对机器的负担比较重，因此需要进一步调优索引性能。
> 2. 处理历史消息的策略。有些群可能包含非常多的历史消息，全部索引不现实。

说一下我的思考，不成熟，见谅。
- 1 不知能否异步加载，也就是按时间线，每次点击下一页后才索引下一组100条。这样能减少索引压力
- 2 就常见的微信qq搜索功能来说，搜索也是只从开启搜索这一刻开始后的记录。。也就是说可以直接放弃运行bot之前的历史记录。

**Comment by SharzyL** [comment]
在改进索引逻辑之后，现在的性能应该能够应对所有聊天的索引需求，近期将计划重构来实现这个功能。

**Comment by SharzyL** [comment]
新版本 (abfe2d7e85f2d0f208baf5db4834b5b0fcdefad2) 已支持默认监听所有聊天，详见 README.md 中的介绍，欢迎试用

**Comment by artxia** [comment]
大佬牛掰！这两天部署试试！
