### ISSUE TITLE
运行到docker start -ia tg_searcher时报错failed to resize tty, using default size该如何解决

### ISSUE THREAD

**Issue by Levisper** [SharzyL/tg_searcher#15]
**Bug 描述**
参考docker-compose部署，运行到docker start -ia tg_searcher时报错 failed to resize tty, using default size。

**复现方式**
复现 bug 的步骤：
参考docker-compose部署，运行到docker start -ia tg_searcher时报错。
文件目录架构：
└─ tg_searcher
   ├─ config
   |  └─ searcher.yaml
   └─ docker-compose.yaml
   
**日志**
[root@1 tg_searcher]# docker start -ia tg_searcher
container aeaa34cc2f71793a514960a20ced4f918881398280c226c8df38b58482c7292c is restarting, wait until the container is running
failed to resize tty, using default size。

**Comment by SharzyL** [comment]
第一行的报错是主要原因，`docker stop aeaa34cc2f71793a514960a20ced4f918881398280c226c8df38b58482c7292c` 试试

**Comment by Levisper** [comment]
感谢，已解决！还有个问题想请教一下，bot读取的消息会不会缓存在服务器，需要定期清理吗，不知道缓存会不会很大

**Comment by SharzyL** [comment]
bot 只会存储文字，不会存储二进制的图片文件等内容。根据我的实际使用情况，存储了接近 20 万条消息的服务器占用的存储空间大约是 180MB。并且索引是一个类似于哈希表的结构，它的磁盘空间占用不是严格线性增长的，所以再增加几倍消息数量不一定会增加几倍的存储占用。非极端情况下应该不用担心磁盘占用问题。

**Comment by Levisper** [comment]
好的，感谢作者你开发了这么好的一个项目！
