### ISSUE TITLE
在群组里用不了

### ISSUE THREAD

**Issue by ghost** [SharzyL/tg_searcher#2]
私聊可以查询到，但是群组中不行，总是返回群组的 ID。
多次测试发现私聊 bot 有时也不行，有点玄学😂

**Comment by ghost** [comment]
https://github.com/SharzyL/tg_searcher/blob/2a375257f9ba1d329983d0c6f7d32464e16b1a2b/main.py#L246-L248
测试了下看来是直接抛异常了
不过异常 e 为什么就返回一个群组 ID？

**Comment by seirachan** [comment]
多次测试发现私聊 bot 有时也不行，有点玄学😂

**Comment by SharzyL** [comment]
把上面这几行错误处理代码后面加上一行 `raise e`，然后重新运行一下看看？

这样之后会出现错误会在日志里面打印出一个更完整的调用栈，然后你可以把调用栈发过来更方便 debug 和讨论

**Comment by ghost** [comment]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telethon/client/updates.py", line 467, in _dispatch_update
    await callback(event)
  File "main.py", line 237, in bot_message_handler
    raise e
  File "main.py", line 231, in bot_message_handler
    respond = render_respond_text(result, used_time, is_private)
  File "main.py", line 128, in render_respond_text
    respond += f'<b>{id_to_title[hit["chat_id"]]} [{hit["post_time"]}]</b>\n'
KeyError: -100xxxxxx(群 ID)
```
我 print 了一下 respond，发现历史消息的 chat_id 都是正数，运行 bot 后新增的消息里面都是原始 ID 即负数，应该是每次更新消息时候 chat_id 没改成正数
https://github.com/SharzyL/tg_searcher/blob/2a375257f9ba1d329983d0c6f7d32464e16b1a2b/main.py#L107

基本确定了是这里新增的消息没有转换 chat_id，尝试搜寻今天没提过的关键词都正常返回了。
看上去这应该是个 bug👀

**Comment by ghost** [comment]
https://github.com/SharzyL/tg_searcher/blob/2a375257f9ba1d329983d0c6f7d32464e16b1a2b/main.py#L107
好像只需要改成这样
```python
 chat_id=get_share_id(event.chat_id), 
```
