### ISSUE TITLE
/clear should probably not clear all indices

### ISSUE THREAD

**Issue by DDVD233** [SharzyL/tg_searcher#20]
当前 /clear 指令会删除所有 index，但是由于 /clear 是菜单栏的选项之一，容易误触导致丢失所有索引。

可能更好的方式是使用 /clear all 之类的指令来清除所有 Index，同时让无参数的 /clear 不做任何事。

一点建议，如有打扰十分抱歉。

**Comment by SharzyL** [comment]
Resolved

**Comment by DDVD233** [comment]
Thanks!
