### ISSUE TITLE
/download_chat 下载未关注频道导致bot崩溃

### ISSUE THREAD

**Issue by despacito008** [SharzyL/tg_searcher#21]
**Bug 描述**
/download_chat 下载未关注频道导致bot崩溃

**Comment by SharzyL** [comment]
这不算是崩溃，只是没有特别处理报错信息。由于 Telegram 的机制，对于没有关注的频道，无法从 id 来获得频道的信息，在调用 `get_input_entity` 的时候会抛出异常。

**Comment by SharzyL** [comment]
> /download_chat 信息没下载完全，索引了2w条，但只下载了5k条 请问是api原因吗

能否提供更详细的信息，2w 和 5k 这两个数字是怎样获知的？

**Comment by SharzyL** [comment]
resolved
