### ISSUE TITLE
Cannot connect to redis server ('localhost', 6379): Error 99 connecting to localhost:6379

### ISSUE THREAD

**Issue by despacito008** [SharzyL/tg_searcher#26]
**Bug 描述**
请问这个redis问题怎么解决，已经有了redis容器
x:~/tg_searcher$ docker start -ia tg_searcher 
INFO:telethon.network.mtprotosender:Connecting to ip:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to ip:443/TcpFull complete!
INFO:telethon.client.users:Phone migrated to 5
INFO:telethon.client.telegrambaseclient:Reconnecting to new data center 5
INFO:telethon.network.mtprotosender:Disconnecting from ip:443/TcpFull...
INFO:telethon.network.mtprotosender:Disconnection from ip:443/TcpFull complete!
INFO:telethon.network.mtprotosender:Connecting to ip:443/TcpFull...
INFO:telethon.network.mtprotosender:Connection to ip:443/TcpFull complete!
Please enter the code you received: 62211
Please enter your password: 
Invalid password. Please try again
Please enter your password: 
Signed in successfully as x
INFO:session:alice:Start iterating dialogs
INFO:session:alice:End iterating dialogs, 1493 dialogs in total
INFO:bot-backend:pub_index:Init backend bot
CRITICAL:bot-frontend:public:Cannot connect to redis server ('localhost', 6379): Error 99 connecting to localhost:6379. Cannot assign requested address.

**复现方式**
复现 bug 的步骤：
1. 使用 tg_searcher 的最新版本 ...（使用 git log 等工具查看当前的 commit）
2. 使用了配置文件
```yaml
common:
  name: sharzy_test
  runtime_dir: /var/lib/tg_searcher
  api_id: x
  api_hash: x
...
frontends:
  - type: bot
    id: public
    use_backend: pub_index
    config:
      admin_id: x
      bot_token: x
...
backends:
  - id: pub_index
    use_session: alice
...

**Comment by SharzyL** [comment]
注意配置文件中 redis 的地址应当配置为 `redis:6379` 而不是 `localhost:6379`

**Comment by despacito008** [comment]
> 注意配置文件中 redis 的地址应当配置为 `redis:6379` 而不是 `localhost:6379`

好的 已解决谢谢

**Comment by despacito008** [comment]
另外 /download_history 能否根据时间参数来获取历史记录

**Comment by SharzyL** [comment]
暂无支持，如果有需要可以提 pr 或另提 issue （不一定近期实现）
