### ISSUE TITLE
searcher.yaml 示例文件是否有问题？

### ISSUE THREAD

**Issue by artxia** [SharzyL/tg_searcher#8]
运行后报错
```
KeyError: 'private'
sys:1: RuntimeWarning: coroutine 'BotFrontend.start' was never awaited
sys:1: RuntimeWarning: coroutine 'BackendBot.start' was never awaited

```

将`searcher.yaml`  内这个位置的`private`改为`personal` 后可以运行。但是 tg里面一直弹出`当前索引为空，请先 /download_history 建立索引`
```
  - type: bot
    id: private
    use_backend: private
```

**Comment by artxia** [comment]
刚发完又注意到您更新了 README.md  https://github.com/SharzyL/tg_searcher/commit/8b48e55c6b3fc8217fc2ec92b69220736429ae82
采用最新版的 searcher.yaml 示例依然有问题。
use_backend 和 backends id 是否需要对应？

**Comment by SharzyL** [comment]
在 8b48e55c6b3fc8217fc2ec92b69220736429ae82 中已修复，use_backend 和 backends id 确实需要对应
